require:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.4
  NewCops: enable

Layout/LineLength:
  Max: 80

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"

RSpec:
  Enabled: true
