plugins:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.4
  NewCops: enable

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 100

Lint/MissingSuper:
  AllowedParentClasses:
    - Strategies::OfferStrategy
    - Strategies::DeliveryStrategy

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"

RSpec:
  Enabled: true

RSpec/MultipleExpectations:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false
